  services:
    db:
      build:
        context: ./db
        dockerfile: Dockerfile
      container_name: anomaly_db
      environment:
        POSTGRES_DB: anomaly_data
        POSTGRES_USER: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
        # No password set — peer authentication assumed
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
    
    data_gen_service:
      build:
        context: ./data_gen_service
        dockerfile: Dockerfile
      depends_on:
        - db
      environment:
        - PGHOST=db
      command: python data_feed.py
      restart: always


    app:
      build: 
        context: ./mcp_client_server
        dockerfile: Dockerfile
      env_file:
        - .env
      depends_on:
        - db
      environment:
        - PGHOST=db
      command: python mcp_client/client.py mcp_server/server.py
      restart: always

  volumes:
    pgdata:
