  version: '3.9'

  services:
    db:
      image: birex-mcp-v1-db
      container_name: anomaly_db
      environment:
        POSTGRES_DB: anomaly_data
        POSTGRES_USER: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
        # No password set — peer authentication assumed
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always

    app:
      image: birex-mcp-v1-app
      env_file:
        - .env
      depends_on:
        - db
      environment:
        - PGHOST=db
      command: python mcp_client/client.py mcp_server/server.py
      restart: always

  volumes:
    pgdata:
